// AUTH ACTIONS
export const AUTH_CHANGED = "AUTH_CHANGED"
export const EMAIL_AUTH = "EMAIL_AUTH"
export const EMAIL_AUTH_SUCCESS = 'EMAIL_AUTH_SUCCESS'
export const EMAIL_AUTH_FAIL = "EMAIL_AUTH_FAIL"
export const EMAIL_REGISTER = "EMAIL_REGISTER"
export const EMAIL_REGISTER_SUCCESS = "EMAIL_REGISTER_SUCCESS"
export const EMAIL_REGISTER_FAIL = "EMAIL_REGISTER_FAIL"